version: '3.9'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    build: .
    container_name: express_backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend_network

volumes:
  db_data:

networks:
  backend_network:
    driver: bridge