version: '3.9'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    build: .
    container_name: express_backend
    ports:
      - "4000:4000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: myapp
      POSTGRES_HOST: db
    depends_on:
      - db
    networks:
      - backend_network

volumes:
  db_data:

networks:
  backend_network:
    driver: bridge