import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter", // keep if you still want the CSS var for Tailwind
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}> {/* ← this sets font-family: Inter */}
      <body className="antialiased">            {/* no need for font-sans here */}
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}