import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContext } from "@/context/AuthContext";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter", // keep if you still want the CSS var for Tailwind
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <AuthContext>{children}</AuthContext>
      </body>
    </html>
  );
}